### PR TITLE
Collab

### PR DESCRIPTION
**Pull request by mugdhapolimera**

### CODE REVIEW

**Comment by mugdhapolimera** [comment]
I noticed that some affiliation related assertion failed. This is not for any new file that I uploaded. @seasidesparrow is this related to one of your recent PRs?

**Comment by seasidesparrow** [comment]
It looks like your original test output was based on the old version of affPubID, but this field is now an array of AffID objects.  However, the parser isn't outputting what I would expect -- it's assigning all the pubIDs for all of an authors institution to each institution.  For example, `000000041936754X` and `grid.38142.3c` are just for Harvard University, not for all three institutions.

**Comment by mugdhapolimera** [comment]
@seasidesparrow I didn't change anything related to the affid stuff in this PR. Could it be a bug from the other commit?

**Review by seasidesparrow — APPROVED** [review]
Looks good, merge at your convenience.  I'll make an issue for the repeated identifiers now.

**Pull request merged**
